services:

  # mysql
 
  dataBase:
    container_name: mysql-database
    image: mysql:8.0
    ports: 
     - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: weather_data
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1
    volumes:
      - mysqlVolume:/var/lib/mysql
    networks:
      - mynetwork


  # python

  etlWorker:
    image: mypy
    container_name: etl_worker
    restart: always
    working_dir: /usr/src/app
    command: ["python", "tableCreation.py"]
    depends_on:
     - dataBase
    networks:
     - mynetwork


# jenkins

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: always
    ports:
     - "8080:8080"
     - "50000:50000"
    volumes:
     - jenkinsVolume:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - JENKINS_USER=admin
     - JENKINS_PASS=admin
    networks:
     - mynetwork

volumes:
  mysqlVolume:
  jenkinsVolume:
  
networks:
  mynetwork:
    driver: bridge