services:

  # mysql - etl tests
 
  dataBase:
    container_name: mysql-database
    image: mysql:8.0
    ports: 
     - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: weather_data
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1
    volumes:
      - mysqlVolume:/var/lib/mysql
    networks:
      - mynetwork

# PostgreSQL - Airflow data base
  postgres:
    image: postgres:15
    container_name: airflow-postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    volumes:
      - postgresVolume:/var/lib/postgresql/data
    networks:
      - mynetwork

  # Apache Airflow
  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow_container
    restart: always
    command: webserver
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - postgres
      - dataBase

volumes:
  mysqlVolume:
  postgresVolume:

networks:
  mynetwork:
    driver: bridge
